In [3]:
import pandas as pd
import numpy as np

In [5]:
import numpy as np

# Method 1: Using np.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array1


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Method 2: Using np.zeros() and then filling the array
array2 = np.zeros((2, 3))
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]
array2


array([[1., 2., 3.],
       [4., 5., 6.]])

array([1., 2., 3.])

In [7]:
# Method 3: Using np.full()
array3 = np.full((2, 3), 0)
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]
array3


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# 2
np1=np.linspace(1,100,10)
np1

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [14]:
np1.reshape(2,5)

array([[  1.,  12.,  23.,  34.,  45.],
       [ 56.,  67.,  78.,  89., 100.]])

# 3
np.array: Always creates a new array.

np.asarray: Converts to an array without copying if the input is already an array.

np.asanyarray: Similar to np.asarray, but retains subclasses of np.ndarray.

Shallow Copy: Copies the structure but not the nested objects (references to original objects are maintained).

Deep Copy: Copies both the structure and the nested objects (independent copies of objects are made).

In [32]:
#4
arr=np.random.uniform(1,20,20)
arr

array([ 5.66594281,  3.15257314,  8.97309875, 10.30359081, 11.96497067,
       19.54130904, 14.08605051, 15.81556972,  3.88466139, 12.36815186,
       11.34984462,  6.8604319 , 18.99741184,  7.072582  ,  2.22411726,
        3.43987786, 11.34746548, 12.63100512, 12.06289474,  9.71751014])

In [33]:
np.round(arr)

array([ 6.,  3.,  9., 10., 12., 20., 14., 16.,  4., 12., 11.,  7., 19.,
        7.,  2.,  3., 11., 13., 12., 10.])

In [25]:
# 5
arr=np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [29]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [35]:
#6
arr=np.random.randint(1,11,size=(3,3,3))
arr


array([[[ 8,  6,  9],
        [10,  4,  6],
        [ 8,  3,  9]],

       [[ 2,  6,  8],
        [ 2,  1,  9],
        [ 7,  9,  6]],

       [[ 7, 10,  5],
        [ 9,  6,  6],
        [ 2,  6,  5]]])

In [37]:
np.argmax(arr,axis=2)

array([[2, 0, 2],
       [2, 2, 1],
       [1, 0, 1]], dtype=int64)

In [38]:
arr* arr

array([[[ 64,  36,  81],
        [100,  16,  36],
        [ 64,   9,  81]],

       [[  4,  36,  64],
        [  4,   1,  81],
        [ 49,  81,  36]],

       [[ 49, 100,  25],
        [ 81,  36,  36],
        [  4,  36,  25]]])

In [6]:
# 7. 
df = pd.read_csv("People Data.csv")
df.head()

Index          User Id First Name Last Name  Gender  \
0      1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1      2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2      3  810Ce0F276Badec     Sheryl    Lowery  Female   
3      4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4      5  9afFEafAe1CBBB9    Lindsey      Rice  Female   

                           Email               Phone Date of birth  \
0            pwarner@example.org        857.139.8239    27-01-2014   
1  fergusonkatherine@example.net                 NaN    26-07-1931   
2            fhoward@example.org       (599)782-0605    25-11-2013   
3          zjohnston@example.com                 NaN    17-11-2012   
4               elin@example.net  (390)417-1635x3010    15-04-1923   

                  Job Title  Salary  
0         Probation officer   90000  
1                    Dancer   80000  
2                      Copy   50000  
3  Counselling psychologist   65000  
4       Biomedical engineer  100000

In [18]:
df["Phone"].isna().sum()

21

In [15]:
df.head()

Index          User Id First Name Last Name  Gender  \
0      1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1      2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2      3  810Ce0F276Badec     Sheryl    Lowery  Female   
3      4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4      5  9afFEafAe1CBBB9    Lindsey      Rice  Female   

                           Email               Phone Date of birth  \
0            pwarner@example.org        857.139.8239    27-01-2014   
1  fergusonkatherine@example.net                 NaN    26-07-1931   
2            fhoward@example.org       (599)782-0605    25-11-2013   
3          zjohnston@example.com                 NaN    17-11-2012   
4               elin@example.net  (390)417-1635x3010    15-04-1923   

                  Job Title  Salary  
0         Probation officer   90000  
1                    Dancer   80000  
2                      Copy   50000  
3  Counselling psychologist   65000  
4       Biomedical engineer  100000

In [20]:
import pandas as pd
import re


# Function to clean phone numbers
def clean_phone_number(phone):
    # Remove all non-numeric characters
    phone = re.sub(r'\D', '', phone)
    
    # Check if the phone number has the correct length (10 digits for US numbers)
    if len(phone) == 10:
        return f"({phone[:3]}) {phone[3:6]}-{phone[6:]}"
    elif len(phone) == 11 and phone[0] == '1':
        return f"({phone[1:4]}) {phone[4:7]}-{phone[7:]}"
    else:
        return phone  # Or handle invalid numbers as needed

# Apply the function to the 'phone' column
df['clean_phone'] = df['Phone'].apply(clean_phone_number)

# Display the cleaned phone numbers
print(df)




TypeError: expected string or bytes-like object, got 'float'

In [39]:
df.dtypes

Index             int64
User Id          object
First Name       object
Last Name        object
Gender           object
Email            object
Phone            object
Date of birth    object
Job Title        object
Salary            int64
dtype: object

In [40]:
df.describe()

Index         Salary
count  1000.000000    1000.000000
mean    500.500000   74640.000000
std     288.819436   16136.318687
min       1.000000   50000.000000
25%     250.750000   60000.000000
50%     500.500000   80000.000000
75%     750.250000   90000.000000
max    1000.000000  100000.000000

In [22]:
# 8
df.iloc[50:]

Index          User Id First Name Last Name  Gender  \
50      51  CccE5DAb6E288e5         Jo    Zavala    Male   
51      52  DfBDc3621D4bcec     Joshua     Carey  Female   
52      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
53      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
54      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                          Email                   Phone Date of birth  \
50         pamela64@example.net  001-859-448-9935x54536    23-11-1992   
51    dianashepherd@example.net    001-274-739-8470x814    07-01-1915   
52    ingramtiffany@example.org        241.179.9509x498    01-07-1910   
53   carriecrawford@example.org       207.797.8345x6177    27-07-1982   
54   fuentesclaudia@example.net    001-599-042-7428x143    06-01-1998   
..                          ...                     ...           ...   
995      lyonsdaisy@example.net            021.775.2933    05-01-1959   
996     dariusbryan@example.com    001-149-710-7799x721    06-10-2001   
997      georgechan@example.org   +1-750-774-4128x33265    13-05-1918   
998         wanda04@example.net           (915)292-2254    31-08-1971   
999     deannablack@example.org      079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
50                      Nurse, adult   80000  
51               Seismic interpreter   70000  
52                         Barrister   60000  
53              Engineer, structural  100000  
54                   Producer, radio   50000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[950 rows x 10 columns]

In [28]:
filtered_data=df[[ 'Last Name', "Gender","Email","Phone","Salary"]]

In [29]:
filtered_data.head()

Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000

In [37]:
filtered_data["Salary"].tail(5)

995     90000
996     50000
997     60000
998    100000
999     90000
Name: Salary, dtype: int64

In [44]:
# 9
filtered_df = df[(df['Last Name'].str.contains('Duke')) & 
                 (df['Gender'] == 'Female') & 
                 (df['Salary'] < 85000)]

In [45]:
filtered_df

Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000

In [51]:
# 10
random_integers = np.random.randint(1, 6, size=35)

reshaped_integers = random_integers.reshape(7, 5)


df = pd.DataFrame(reshaped_integers)


print("Generated DataFrame:")
print(df)


Generated DataFrame:
   0  1  2  3  4
0  1  4  5  5  2
1  5  4  2  4  4
2  1  4  5  2  3
3  3  2  3  5  1
4  3  2  5  2  5
5  5  3  2  4  3
6  5  5  2  1  2
